### ISSUE TITLE
Syntax hilighting view is different than example picture at overview page

### ISSUE THREAD

**Issue by edp1096** [BattleBas/kivy-vscode#1]
How can I make it like example?

Sorry for pour English.

![syntaxhilight](https://user-images.githubusercontent.com/15924482/33062376-6e8c1f14-cee2-11e7-9b0c-791a24de0589.png)

**Comment by BattleBas** [comment]
What color theme for Visual Code are you using? 
I noticed that when I use "Dark (Visual Studio)" it looks like what you are seeing , but when I select "Dark+ (default dark)" then it does work and looks like the example I provided.

**Comment by edp1096** [comment]
You're right.
My theme was Dark (Visual Studio).
I changed theme to default.

Thanks @BattleBas .
