### ISSUE TITLE
No syntax highlight

### ISSUE THREAD

**Issue by nem8** [BattleBas/kivy-vscode#10]
I just started using your extension as im exploring kivy and i have no syntax highlighting.
Anything i can do to fix this? Im not terribly used to vscode.

![image](https://user-images.githubusercontent.com/495296/38380931-82fb8fc4-3905-11e8-814a-dd02fb5d5c64.png)

**Comment by BattleBas** [comment]
Looks like for your widget rule `<TestAppBoxLayout>` you are missing a colon.
Please try changing it to look like:
`<TestAppBoxLayout>:`

Let me know if that works for you. For an example in the kivy documentation please go [here](https://kivy.org/docs/gettingstarted/rules.html).

Thank you for trying the extension.

**Comment by BattleBas** [comment]
No worries, thanks!
