### ISSUE TITLE
Option To Disable checkForKivyHeader

### ISSUE THREAD

**Issue by Enteleform** [BattleBas/kivy-vscode#12]
I'm currently getting the `Kivy files require #:kivy !` error on my `kv` files, which also causes my explorer view to show that there are issues within the workspace.

The version header is optional, and should not cause an error since Kivy is able to function just fine without it. IMO writing out the Kivy version in each layout file is redundant since a project's Kivy version should be managed via its virtual environment dependency, and the maintainer should be accountable for updating layouts accordingly should the dependency version be changed.

Please add a setting so that users can disable the error checking that causes this issue.

**Comment by BattleBas** [comment]
The Kivy documentation does say ["The content of the file should always start with the Kivy header"](https://kivy.org/doc/stable/api-kivy.lang.html) but I do like your idea that the virtual environment should manage it.

Would it be possible for you to submit a pull request? Might be a little while before I can get around to this. Thanks!

**Comment by Enteleform** [comment]
@BattleBas Awesome, thanks for implementing this 👍

**Comment by BattleBas** [comment]
@Enteleform ok I've pushed the change with version 0.3.0
Enjoy!
