### ISSUE TITLE
Your extension is affected by event stream and have been blocked

### ISSUE THREAD

**Issue by auchenberg** [BattleBas/kivy-vscode#17]
Hi,

Kenneth here from the VS Code team. 

Your extension is affected by https://code.visualstudio.com/blogs/2018/11/26/event-stream, and we have blocked your extension.

In order to enable your extension again the workflow is:
  
1) Fix the extension, submit an update to the marketplace
2) Send mail to VSMarketplace@microsoft.com and kennau@microsoft.com and notify us.
3) We will verify that the extension is okay
4) Our marketplace will publish the extension again and we'll remove the extension from the blocklist

**Comment by BattleBas** [comment]
@auchenberg thank you for letting me know about this issue. I've submitted an update to the marketplace that fixes the extension (version 0.4.0). I've also sent a mail to the addresses you've listed.

Just let me know if there are any other issues.

**Comment by auchenberg** [comment]
We have run validation of your extension and lifted the block.
