### ISSUE TITLE
Syntax Highlighting breaks when using '<' comparison operator

### ISSUE THREAD

**Issue by Demalpheus** [BattleBas/kivy-vscode#18]
As an example, when using an if statement inside a kv file and using the '<' operator, the remainder of the document will be highlighted as a Kivy element

![image](https://user-images.githubusercontent.com/28327241/49535496-5765c080-f892-11e8-8f63-b589c123dcaf.png)

**Comment by BattleBas** [comment]
@Demalpheus thank you for reporting this issue, I created a fix for with the assumption that class rules e.g. `<ClassName>:` don't start with spaces so it won't recgonize "1 < 2" as a candidate.

Can you confirm this is a correct assumption? Checking the documentation I don't see an example that goes against it (https://kivy.org/doc/stable/api-kivy.lang.html)

Here is a screenshot of how it should look after I merge the change:
![capture](https://user-images.githubusercontent.com/3441183/49746966-ffe79c00-fc67-11e8-8853-c5d5b12022de.PNG)

**Comment by Demalpheus** [comment]
@BattleBas, I believe that is correct.

**Comment by BattleBas** [comment]
Great! I pushed the change with version 0.5.0

**Comment by Demalpheus** [comment]
Confirmed working in 0.5.0. Thanks for the quick turnaround!
