### ISSUE TITLE
Starting Kivy in VS Code

### ISSUE THREAD

**Issue by eidolescense** [BattleBas/kivy-vscode#25]
Hi so this is my first time using Kivy and Visual Studio Code though I am familiar with python(im a student and don't understand all the terminology) and have been having trouble trying to set it up/run any code. I've arranged it so VS Code recognizes that Kivy is python but whenever I use import statements, it doesn't recognize it and I get the error: 
Traceback (most recent call last):
  File "c:\Users\PC\Downloads\AnxietyBegone\test.kv", line 1, in <module>
    from kivy.app import App
ModuleNotFoundError: No module named 'kivy'

Is there a specific thing I'm supposed to use to start it/make it work? Sorry if I sound stupid and unexperienced but I am. I tested the "npm install" and didn't really get anything back/working. Or does the Kivy extension not display the interface if I run and have to use something else? DO I need to have a native download of Kivy on my computer for it to work? I'm just very confused and would like some help please.

**Comment by BattleBas** [comment]
Hello! This repository is just for the visual studio code extension that enables syntax highlighting for the kv langauge (https://kivy.org/doc/stable/guide/lang.html).

It sounds like you need help setting up your Kivy development environment, I suggest reading through the kivy documentation here: https://kivy.org/doc/stable/gettingstarted/intro.html
You will probably get better help with your questions in the Kivy forum: https://kivy.org/#forum

To help you get started, the error "no module named 'kivy'" means you haven't installed the Kivy module (e.g. pip install kivy). For your environment setup follow the guides here: https://kivy.org/doc/stable/gettingstarted/installation.html

You don't need npm to develop Kivy apps, that is just for visual studio code extension development. Hope that helps!
