### ISSUE TITLE
Single quotes not recognized as string for syntax highlighting

### ISSUE THREAD

**Issue by vwtimah** [BattleBas/kivy-vscode#5]
See attached image where double quoted text is colored correctly and single quotes are ignored.

![kivyquotes](https://user-images.githubusercontent.com/3092072/33147421-adf747a6-cf95-11e7-8c45-b1667ac546b6.jpg)

**Comment by BattleBas** [comment]
Good catch, I've added the support for single quotes in version 0.2.0 please update to use these changes.
If it doesn't work for you feel free to re-open this issue.

It should look like this now:
![example](https://user-images.githubusercontent.com/3441183/33189197-22f4d872-d066-11e7-9498-57294d698d84.PNG)
_(Note that I am using the color theme Dark+ (default dark) for this screenshot)_
