### ISSUE TITLE
Having a colon within a double quoted string breaks ending of the string highlighting

### ISSUE THREAD

**Issue by vwtimah** [BattleBas/kivy-vscode#6]
See attached image where adding a colon within a double quoted string causes the rest of the code to be highlighted as a string until the next double quote occurs.

![kivycolon](https://user-images.githubusercontent.com/3092072/33147870-8b36da9a-cf97-11e7-9883-5ceeecae63cc.jpg)

**Comment by BattleBas** [comment]
Nice find! I've updated the regular expression that handles syntax highlighting to only capture the first instance of a text with a colon. I've published these changes with version 0.2.0, please update to use these changes. Thank you.

It should look like this now:
![example](https://user-images.githubusercontent.com/3441183/33189305-03cc0eba-d067-11e7-8eb8-921753e47e56.PNG)
_(Note that I am using the color theme Monokai Dimmed for this screenshot)_
